# Generated by Django 2.0 on 2017-12-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0003_auto_20171220_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.ImageField(upload_to='static/Instagram/images'),
        ),
    ]
