# Generated by Django 2.0 on 2018-01-03 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0005_auto_20180102_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=150)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Instagram.Document')),
            ],
        ),
    ]
