# Generated by Django 2.0 on 2018-01-04 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0007_auto_20180103_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID')),
                ('choice', models.CharField(
                    choices=[('Nature', 'NATURE'), ('Sports', 'SPORTS'),
                             ('Code', 'CODE'), ('Animals', 'ANIMALS'),
                             ('Other', 'OTHER')],
                    default='',
                    max_length=2)),
            ], ),
        migrations.AddField(
            model_name='document',
            name='choosing',
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to='Instagram.Topics'),
            preserve_default=False, ),
    ]
