# Generated by Django 2.0 on 2018-01-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0008_auto_20180104_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='choice',
            field=models.CharField(choices=[('Nature', 'NATURE'), ('Sports', 'SPORTS'), ('Code', 'CODE'), ('Animals', 'ANIMALS'), ('Other', 'OTHER')], default='', max_length=7),
        ),
    ]
