# Generated by Django 2.0 on 2018-01-04 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instagram', '0009_auto_20180104_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Instagram.Document'),
        ),
        migrations.AlterField(
            model_name='topics',
            name='choice',
            field=models.CharField(max_length=8),
        ),
    ]
